---
grails:
    profile: web-plugin
    codegen:
        defaultPackage: org.grails.plugin.springsecurity.saml
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    plugin:
        springsecurity:
            userLookup:
                  userDomainClassName: 'test.TestSamlUser'
                  usernamePropertyName: 'username'
                  enabledPropertyName: 'enabled'
                  passwordPropertyName: 'password'
                  authorityJoinClassName: 'test.TestUserRole'
            requestMap:
                  className: 'test/TestRequestmap'
                  urlField: 'urlPattern'
                  configAttributeField: 'rolePattern'
            authority:
                  className: 'test.testRole'
            saml:
                  userAttributeMappings:
                      username: 'username'
                  active: true
                  afterLoginUrl: '/'
                  afterLogoutUrl: '/'
                  userGroupAttribute: 'memberOf'
                  responseSkew: 60
                  autoCreate:
                       active: false
                       key: 'username'
                       assignAuthorities: true
                  metadata:
                       defaultIdp: 'localhost:default:entityId'
                       url: '/saml/metadata'
                       providers:
                           ping: 'security/idp-local.xml'
                       sp:
                           file: 'security/sp.xml'
                           defaults:
                                local: true
                                signingKey: 'ping'
                  keyManager:
                        storeFile: 'classpath:security/keystore.jks'
                        storePass: 'nalle123'
                        passwords:
                            ping: 'ping123'
                        defaultKey: 'ping'
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

endpoints:
    jmx:
        unique-names: true

environments:
    test:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
