grails:
    plugin:
        springsecurity:
            saml:
                loginNonce: false
                userAttributeMappings: {}
                active: true
                afterLoginUrl: '/'
                afterLogoutUrl: '/'
                userGroupAttribute: 'memberOf'
                autoCreate:
                    active: false
                    key: 'username'
                    assignAuthorities: true
                metadata:
                    timeout: 5000
                    defaultIdp: ''
                    providers: {}
                    sp:
                        file: 'security/sp.xml'
                        defaults:
                            alias: 'test'
                            signingKey: 'ping'
                keyManager:
                    storeFile: 'classpath:security/keystore.jks'
                    storePass: 'nalle123'
                    passwords:
                        ping: 'ping123'
